# Generated by Django 5.2.1 on 2025-05-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_userprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_balance_cached',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_earnings_cached',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
