# Generated by Django 5.2.1 on 2025-05-17 14:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_userprofile_current_balance_cached_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('trader_id_display', models.CharField(help_text='Publicly visible Trader ID', max_length=20, unique=True)),
                ('profile_image', models.ImageField(blank=True, help_text='Optional: 200x200px recommended', null=True, upload_to='trader_profiles/')),
                ('strategy', models.CharField(choices=[('SCALPING', 'Scalping'), ('SWING', 'Swing Trading'), ('POSITION', 'Position Trading'), ('ALGORITHMIC', 'Algorithmic'), ('DAY_TRADING', 'Day Trading'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('strategy_description', models.TextField(blank=True, help_text='More detailed description of the trading strategy.')),
                ('current_roi_monthly', models.DecimalField(decimal_places=2, default=0.0, help_text='Current estimated monthly ROI %', max_digits=5)),
                ('win_rate_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Historical win rate %', max_digits=5)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], default='MEDIUM', max_length=10)),
                ('bio', models.TextField(blank=True)),
                ('experience_years', models.PositiveIntegerField(default=1)),
                ('joined_platform_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True, help_text='Is this trader currently active and available for assignment?')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='assigned_trader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='landing.trader'),
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('profit_loss_since_last', models.DecimalField(decimal_places=2, default=0.0, help_text='P/L since the previous snapshot for this user', max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
