# Generated by Django 5.2.1 on 2025-05-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_platformannouncement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='initial_investment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='investment_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
