# Generated by Django 5.2.1 on 2025-05-19 12:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_dailyprofitlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_cycle_principal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Principal for the current active cycle's growth calculation.", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_cycle_start_date',
            field=models.DateField(blank=True, help_text='Start date of the current active investment cycle.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_awaiting_reinvestment_action',
            field=models.BooleanField(default=False, help_text='True if current cycle ended and user needs to decide on reinvestment.'),
        ),
        migrations.CreateModel(
            name='DailyLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opening_gross_managed_capital', models.DecimalField(decimal_places=2, max_digits=12)),
                ('daily_gross_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('user_profit_share_percentage', models.DecimalField(decimal_places=2, help_text='e.g., 50.00 for 50%', max_digits=5)),
                ('user_profit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('platform_profit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('user_opening_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('user_closing_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Daily Ledger Entries',
                'ordering': ['user', 'date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
