# Generated by Django 5.2.1 on 2025-05-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_userprofile_current_cycle_principal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('PROFIT_PAYOUT', 'Profit Payout'), ('FEE', 'Fee'), ('INITIAL_INVESTMENT', 'Initial Investment'), ('DAILY_SIMULATED_PROFIT', 'Daily Simulated Profit'), ('REINVESTMENT_START', 'Reinvestment Cycle Start')], max_length=30),
        ),
    ]
