# Generated by Django 5.2.1 on 2025-05-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_announcementview'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformannouncement',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Indicates if the user has read this announcement.'),
        ),
    ]
