# Generated by Django 5.2.1 on 2025-05-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_platformannouncement_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformannouncement',
            name='user',
        ),
        migrations.AddField(
            model_name='platformannouncement',
            name='is_global',
            field=models.BooleanField(default=True, help_text='If True, announcement is for all users. If False, select specific users below.'),
        ),
    ]
