# Generated by Django 5.2.1 on 2025-06-04 15:59

import landing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0013_remove_platformannouncement_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to=landing.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='transaction',
            name='related_tier_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('PENDING_APPROVAL', 'Pending Approval'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('PROFIT_PAYOUT', 'Profit Payout'), ('FEE', 'Fee'), ('INITIAL_INVESTMENT', 'Initial Activation'), ('DAILY_SIMULATED_PROFIT', 'Daily Simulated Profit'), ('REINVESTMENT_START', 'Reinvestment Cycle Start'), ('CYCLE_CLOSEOUT', 'Cycle Closeout Adjustment'), ('PENDING_INVESTMENT', 'Pending Investment Deposit')], max_length=30),
        ),
    ]
