# Generated by Django 5.2.1 on 2025-06-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0014_transaction_proof_of_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('PAYOUT', 'Profit Payout'), ('TRADE_SUMMARY', 'Trade Summary'), ('PLATFORM', 'Platform Update'), ('SECURITY', 'Security Alert'), ('TIER_CHANGE', 'Tier Change'), ('GENERAL', 'General Info'), ('PAYMENT_SUBMITTED', 'Payment Submitted')], default='GENERAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='selected_tier',
            field=models.CharField(blank=True, choices=[('basic', 'Basic Package'), ('standard', 'Standard Package'), ('premium', 'Premium Package')], max_length=50, null=True),
        ),
    ]
